/*
-------------------------------------------------------------------------------

    Copyright (c) Charles Carley.

    Contributor(s): none yet.

-------------------------------------------------------------------------------
  This software is provided 'as-is', without any express or implied
  warranty. In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
-------------------------------------------------------------------------------
*/
#include <fstream>
#include <iomanip>
#include <iostream>
#define FT_IN_SOURCE_FILE
#include "Blender.h"
#include "Utils/skStack.h"
#include "Utils/skString.h"
#include "Utils/skTimer.h"
#include "ftCompiler.h"
#include "ftMember.h"
#include "ftPlatformHeaders.h"
#include "ftScanDNA.h"


using namespace std;


struct ProgramInfo
{
    const char* m_progName;
    skString    m_ifile;
    skString    m_ofile;
    skStream*   m_stream;
    void*       m_dnaBlock;
    ftTables*   m_tables;

    // extra vars only valid in extract to file
    string m_outName;
};



using namespace ftFlags;


void writeFileHeader(ProgramInfo& ctx, ostream& out)
{
    char     buf[32];
    SKuint32 br = skGetTimeString(buf, 31, "%a %b %d %r");

    out << "/*" << endl
        << endl;
    out << "    This file was automatically generated by: " << ctx.m_progName << endl;
    if (br != SK_NPOS32)
        out << "    " << buf << endl;
    out << "    https://github.com/CharlesCarley/FileTools" << endl
        << endl;
    out << "*/" << endl;


    ctx.m_outName = ctx.m_ofile.substr(0, ctx.m_ofile.find('.')).c_str();

    out << "#ifndef _" << ctx.m_outName << "_" << endl;
    out << "#define _" << ctx.m_outName << "_" << endl;
}


void writeFileFooter(ProgramInfo& ctx, ostream& out)
{
    out << "#endif//_" << ctx.m_outName << "_" << endl;
}

void writeIndent(ostream& out, int nr, int spacePerIndent = 4)
{
    spacePerIndent = skMax(spacePerIndent - 1, 0);
    int i;
    for (i = 0; i < nr; ++i)
        out << setw(spacePerIndent) << ' ';
}

void writeForward(ProgramInfo& ctx, ostream& out, ftStruct* ftStrc)
{
    out << "struct " << ftStrc->getName() << ';' << endl;
}

void writeStructure(ProgramInfo& ctx, ostream& out, ftStruct* ftStrc)
{
    out << "struct " << ftStrc->getName() << endl;
    out << "{" << endl;
    FBTtype* strc = ctx.m_tables->getStructAt(ftStrc->getStructIndex());

    if (strc)
    {
        FBTtype cnt = strc[1], i;
        strc += 2;

        for (i = 0; i < cnt; ++i, strc += 2)
        {
            char* type = ctx.m_tables->getTypeNameAt(strc[0]);
            char* name = ctx.m_tables->getNameAt(strc[1]).m_name;

            if (type && name)
            {
                writeIndent(out, 1);
                out << type << ' ' << name << ';' << endl;
            }
        }
    }

    out << "};" << endl
        << endl;
}


void writeUnresolved(ProgramInfo& ctx, ostream& out, FBTtype* typeNotFound)
{
    char*         typeName = ctx.m_tables->getTypeNameAt(typeNotFound[0]);
    const ftName& name     = ctx.m_tables->getNameAt(typeNotFound[1]);

    if (name.m_ptrCount > 0)
        out << "typedef void* " << typeName << ";" << endl;
    else
        out << "typedef size_t " << typeName << ";" << endl;
}


int ftStructCMP(ftStruct* a, ftStruct* b)
{
    int ad = a->hasDependantTypes() ? 1 : 0;
    int bd = b->hasDependantTypes() ? 1 : 0;
    return a < b;
}


bool hasUnResolved(skArray<FBTtype*>& unresolved, FBTtype* inp)
{
    bool found = false;

    skArray<FBTtype*>::Iterator it = unresolved.iterator();
    while (!found && it.hasMoreElements())
    {
        FBTtype* type = it.getNext();
        found         = type[0] == inp[0] && type[1] == inp[1];
    }
    return found;
}


void resolveDependenciesRecursive(ProgramInfo&        ctx,
                                  ftStruct*           strcWithDep,
                                  skArray<FBTtype*>&  unresolved,
                                  skArray<ftStruct*>& main,
                                  skArray<ftStruct*>& arr)
{
    FBTtype* strc = ctx.m_tables->getStructAt(strcWithDep->getStructIndex());
    if (strc)
    {
        FBTtype cnt = strc[1], i;
        strc += 2;

        for (i = 0; i < cnt; ++i, strc += 2)
        {
            FBTtype       type  = strc[0];
            const ftName& name  = ctx.m_tables->getNameAt(strc[1]);
            ftStruct*     fstrc = ctx.m_tables->findStructByType(type);

            if (fstrc)
            {
                if (name.m_ptrCount > 0)
                {
                    SKuint32 pos = main.find(fstrc);
                    if (pos != SK_NPOS32)
                    {
                        if (arr.find(fstrc) == SK_NPOS32)
                            arr.push_back(fstrc);
                    }
                }
                else if (type >= ctx.m_tables->getFirstStructType())
                {
                    SKuint32 pos = main.find(fstrc);
                    if (pos != SK_NPOS32)
                    {
                        if (arr.find(fstrc) == SK_NPOS32)
                        {
                            arr.push_back(fstrc);
                            resolveDependenciesRecursive(ctx, fstrc, unresolved, main, arr);
                        }
                    }
                }
            }
            else
            {
                if (!hasUnResolved(unresolved, strc))
                    unresolved.push_back(strc);
            }
        }
    }
}


void sortStructs(ProgramInfo& ctx, skArray<FBTtype*>& unresolved, skArray<ftStruct*>& arr)
{
    skArray<ftStruct*> main = ctx.m_tables->getStructureArray();

    skStack<ftStruct*> stack;
    unresolved.clear();

    skArray<ftStruct*>::Iterator it = main.iterator();
    while (it.hasMoreElements())
    {
        ftStruct* strc = it.getNext();
        if (strc->hasDependantTypes())
            stack.push(strc);
        else
        {
            arr.push_back(strc);
            main.erase(strc);
            it = main.iterator();
        }
    }


    while (!stack.empty())
    {
        ftStruct* strc_with_dep = stack.top();
        stack.pop();
        resolveDependenciesRecursive(ctx, strc_with_dep, unresolved, main, arr);
    }


    if (!unresolved.empty())
    {
        skArray<FBTtype*>::Iterator typeIter = unresolved.iterator();
        while (typeIter.hasMoreElements())
        {
            FBTtype* pair = typeIter.getNext();

            printf("(%d %d) (%s %s)\n",
                   pair[0],
                   pair[1],
                   ctx.m_tables->getTypeNameAt(pair[0]),
                   ctx.m_tables->getNameAt(pair[1]).m_name);
        }
    }


    it = main.iterator();
    while (it.hasMoreElements())
    {
        ftStruct* strc = it.getNext();
        arr.push_back(strc);

        printf("==> %s\n", strc->getName());
    }
}



int extractToFile(ProgramInfo& ctx)
{
    int       status = 0;
    ftTables* tables = ctx.m_tables;

    skArray<FBTtype*>  unresolved;
    skArray<ftStruct*> arr;
    sortStructs(ctx, unresolved, arr);


    ofstream outf;
    ostream& sout = outf;

    outf.open(ctx.m_ofile.c_str());
    if (outf.is_open())
    {
        writeFileHeader(ctx, sout);

        skArray<ftStruct*>::Iterator it = arr.iterator();
        while (it.hasMoreElements())
        {
            ftStruct* strc = it.getNext();
            writeForward(ctx, sout, strc);
        }

        skArray<FBTtype*>::Iterator uit = unresolved.iterator();
        while (uit.hasMoreElements())
        {
            FBTtype* cur = uit.getNext();
            writeUnresolved(ctx, sout, cur);
        }

        it = arr.iterator();
        while (it.hasMoreElements())
        {
            ftStruct* strc = it.getNext();
            writeStructure(ctx, sout, strc);
        }


        writeFileFooter(ctx, sout);
    }
    else
    {
        status = -1;
        cout << "Failed to open the output file " << ctx.m_ofile.c_str() << endl;
    }
    return status;
}



int parseCommandLine(ProgramInfo& ctx, int argc, char** argv)
{
    int i, status = 0;
    for (i = 0; i < argc && status == 0; ++i)
    {
        char* carg = argv[i];

        if (*carg == '-')
        {
            ++carg;
            if (*carg == 'i')
            {
                if (i + 1 < argc)
                    ctx.m_ifile = argv[++i];
                else
                {
                    printf(
                        "Parsed the end of the command line while "
                        "searching for the next input.\n");
                    status = -1;
                }
            }
            else if (*carg == 'o')
            {
                if (i + 1 < argc)
                    ctx.m_ofile = argv[++i];
                else
                {
                    printf(
                        "Parsed the end of the command line while "
                        "searching for the next input.\n");
                    status = -1;
                }
            }
        }
    }

    if (ctx.m_ifile.empty())
    {
        status = -2;
        printf("The input file option (-i <infile>) is required.\n");
    }
    else if (ctx.m_ofile.empty())
    {
        status = -2;
        printf("The output file option (-o <outfile>) is required.\n");
    }

    return status;
}


int getBaseName(const char* input)
{
    int offs = 0;
    if (input)
    {
        int len = ((int)strlen(input)), i;
        for (i = len - 1; i >= 0 && offs == 0; --i)
            if (input[i] == '/' || input[i] == '\\')
                offs = i + 1;
    }
    return offs;
}


void usage(const char* prog)
{
    if (prog)
    {
        printf("%s\n", prog);
        printf("       <options>  -i <infile> -o <outfile>\n");
        printf("\n");
        printf("\n");
        printf("\n");
    }
    else
        printf("Invalid program name supplied to usage.\n");
}

int main(int argc, char** argv)
{
    // the idea of this program is
    // to load any type of file,
    // and scan for a DNA1 chunk
    // and extract the tables.

    char* base   = argv[0] + getBaseName(argv[0]);
    int   status = 0;

    ProgramInfo ctx = {base, "", "", nullptr, nullptr, nullptr};
    if (parseCommandLine(ctx, argc, argv) < 0)
    {
        usage(base);
        return 1;
    }
    else
    {
        ftGzStream fp;
        fp.open(ctx.m_ifile.c_str(), skStream::READ);
        if (fp.isOpen())
        {
            ftScanDNA scanner;
            status = scanner.findHeaderFlags(&fp);
            if (status != FS_OK)
            {
                printf(
                    "Failed to extract the appropriate header "
                    "flags from the supplied file %s.\n",
                    ctx.m_ifile.c_str());
            }
            else
            {
                status = scanner.scan(&fp);
                if (status == FS_OK)
                {
                    ctx.m_dnaBlock = scanner.getDNA();
                    ctx.m_tables   = new ftTables(scanner.is64Bit() ? 8 : 4);

                    status = ctx.m_tables->read(ctx.m_dnaBlock,
                                                scanner.getLength(),
                                                scanner.getFlags(),
                                                ftFlags::LF_ONLY_ERR);
                    if (status == FS_OK)
                    {
                        status = extractToFile(ctx);
                    }
                    else
                    {
                        printf(
                            "Failed to rebuild the DNA table"
                            "from the supplied file %s.\n",
                            ctx.m_ifile.c_str());
                    }
                }
                else
                {
                    printf(
                        "Failed to properly scan to the DNA1 block"
                        "in the supplied file %s.\n",
                        ctx.m_ifile.c_str());
                }
            }
        }
        else
        {
            status = -1;
            printf("Failed to open the input file for reading.\n");
        }
    }

    if (ctx.m_tables)
        delete ctx.m_tables;
    if (ctx.m_dnaBlock)
        free(ctx.m_dnaBlock);
    return status;
}
