name: Build With CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v1
     - name: Configure
       run: cmake -DFileTools_BUILD_TEST=ON -DFileTools_AUTO_RUN_TEST=ON -DFileTools_BUILD_RECOMPILE_TEST=ON -DFileTools_BLEND_FILE=ON -DFileTools_BLEND_TEST=ON .
     - name: Make
       run: make