name: Build With CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v1
     - name: Configure
       run: cmake -DFileTools_BLEND_FILE=ON -DFileTools_BLEND_TEST=ON -DFileTools_TESTS=ON -DFileTools_EXAMPLE_FILE=ON -DFileTools_EXAMPLE_TEST=ON .
     - name: Make
       run: make
     - name: RunTests
       run: ./Tests/FileToolsTests
     - name: RunBlendTests
       run: ./BlendFileTest